version: '3.8'

services:
  frontend:
    build:
      context: ./webpage  # Path to your frontend project folder
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend  # Path to your backend project folder
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/Arcade_db
      - DB_USER=postgres
      - DB_PASS=password123
    depends_on:
      - db
    networks:
      - app-network
    env_file:
      - backend/.env

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: Arcade_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "54325:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: