image: docker:latest

variables:
  DOCKER_IMAGE: "registry.gitlab.com/kdg-ti/the-lab/teams-24-25/project-arcade/backend"
  DOCKER_TAG: "latest"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  JAVA_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=false -Dorg.gradle.console=plain"

stages:
  - build
  - test
  - deploy

before_script:
  - apk add --no-cache bash git openjdk21
  - chmod +x gradlew

build:
  stage: build
  script:
    - ./gradlew build -x test
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 hour

unit_tests:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml

container_build:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build -t "$DOCKER_IMAGE:$DOCKER_TAG" .
    - docker push "$DOCKER_IMAGE:$DOCKER_TAG"
