name: Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build JAR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission to Gradle
        run: chmod +x backend/gradlew

      - name: Build application (excluding tests)
        run: cd backend && ./gradlew build -x test

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-jar
          path: backend/build/libs/*.jar

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission to Gradle
        run: chmod +x backend/gradlew

      - name: Run tests
        run: cd backend && ./gradlew test

      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: backend/build/test-results/test/TEST-*.xml

  deploy:
    name: Build & Push Backend Docker Image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository }}/backend:latest ./backend

      - name: Push Docker Image
        run: docker push ghcr.io/${{ github.repository }}/backend:latest
